//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE322_App_KAU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JohariAttributes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JohariAttributes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IE322_App_KAU.Resources.JohariAttributes", typeof(JohariAttributes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to able.
        /// </summary>
        internal static string attribute1 {
            get {
                return ResourceManager.GetString("attribute1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sentimental.
        /// </summary>
        internal static string attribute10 {
            get {
                return ResourceManager.GetString("attribute10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tense.
        /// </summary>
        internal static string attribute11 {
            get {
                return ResourceManager.GetString("attribute11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accepting.
        /// </summary>
        internal static string attribute12 {
            get {
                return ResourceManager.GetString("attribute12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caring.
        /// </summary>
        internal static string attribute13 {
            get {
                return ResourceManager.GetString("attribute13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dependable.
        /// </summary>
        internal static string attribute14 {
            get {
                return ResourceManager.GetString("attribute14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giving.
        /// </summary>
        internal static string attribute15 {
            get {
                return ResourceManager.GetString("attribute15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingenious.
        /// </summary>
        internal static string attribute16 {
            get {
                return ResourceManager.GetString("attribute16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logical.
        /// </summary>
        internal static string attribute17 {
            get {
                return ResourceManager.GetString("attribute17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to observant.
        /// </summary>
        internal static string attribute18 {
            get {
                return ResourceManager.GetString("attribute18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quiet.
        /// </summary>
        internal static string attribute19 {
            get {
                return ResourceManager.GetString("attribute19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calm.
        /// </summary>
        internal static string attribute2 {
            get {
                return ResourceManager.GetString("attribute2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching.
        /// </summary>
        internal static string attribute20 {
            get {
                return ResourceManager.GetString("attribute20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shy.
        /// </summary>
        internal static string attribute21 {
            get {
                return ResourceManager.GetString("attribute21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trustworthy.
        /// </summary>
        internal static string attribute22 {
            get {
                return ResourceManager.GetString("attribute22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adaptable.
        /// </summary>
        internal static string attribute23 {
            get {
                return ResourceManager.GetString("attribute23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cheerful.
        /// </summary>
        internal static string attribute24 {
            get {
                return ResourceManager.GetString("attribute24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dignified.
        /// </summary>
        internal static string attribute25 {
            get {
                return ResourceManager.GetString("attribute25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to happy.
        /// </summary>
        internal static string attribute26 {
            get {
                return ResourceManager.GetString("attribute26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intelligent.
        /// </summary>
        internal static string attribute27 {
            get {
                return ResourceManager.GetString("attribute27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loving.
        /// </summary>
        internal static string attribute28 {
            get {
                return ResourceManager.GetString("attribute28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organised.
        /// </summary>
        internal static string attribute29 {
            get {
                return ResourceManager.GetString("attribute29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confident.
        /// </summary>
        internal static string attribute3 {
            get {
                return ResourceManager.GetString("attribute3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reflective.
        /// </summary>
        internal static string attribute30 {
            get {
                return ResourceManager.GetString("attribute30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self-assertive.
        /// </summary>
        internal static string attribute31 {
            get {
                return ResourceManager.GetString("attribute31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to silly.
        /// </summary>
        internal static string attribute32 {
            get {
                return ResourceManager.GetString("attribute32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warm.
        /// </summary>
        internal static string attribute33 {
            get {
                return ResourceManager.GetString("attribute33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adaptable.
        /// </summary>
        internal static string attribute34 {
            get {
                return ResourceManager.GetString("attribute34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cheerful.
        /// </summary>
        internal static string attribute35 {
            get {
                return ResourceManager.GetString("attribute35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dignified.
        /// </summary>
        internal static string attribute36 {
            get {
                return ResourceManager.GetString("attribute36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to happy.
        /// </summary>
        internal static string attribute37 {
            get {
                return ResourceManager.GetString("attribute37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intelligent.
        /// </summary>
        internal static string attribute38 {
            get {
                return ResourceManager.GetString("attribute38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loving.
        /// </summary>
        internal static string attribute39 {
            get {
                return ResourceManager.GetString("attribute39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friendly.
        /// </summary>
        internal static string attribute4 {
            get {
                return ResourceManager.GetString("attribute4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organised.
        /// </summary>
        internal static string attribute40 {
            get {
                return ResourceManager.GetString("attribute40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reflective.
        /// </summary>
        internal static string attribute41 {
            get {
                return ResourceManager.GetString("attribute41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self-assertive.
        /// </summary>
        internal static string attribute42 {
            get {
                return ResourceManager.GetString("attribute42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to silly.
        /// </summary>
        internal static string attribute43 {
            get {
                return ResourceManager.GetString("attribute43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warm.
        /// </summary>
        internal static string attribute44 {
            get {
                return ResourceManager.GetString("attribute44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bold.
        /// </summary>
        internal static string attribute45 {
            get {
                return ResourceManager.GetString("attribute45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clever.
        /// </summary>
        internal static string attribute46 {
            get {
                return ResourceManager.GetString("attribute46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to energetic.
        /// </summary>
        internal static string attribute47 {
            get {
                return ResourceManager.GetString("attribute47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to helpful.
        /// </summary>
        internal static string attribute48 {
            get {
                return ResourceManager.GetString("attribute48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to introverted.
        /// </summary>
        internal static string attribute49 {
            get {
                return ResourceManager.GetString("attribute49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to independent.
        /// </summary>
        internal static string attribute5 {
            get {
                return ResourceManager.GetString("attribute5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mature.
        /// </summary>
        internal static string attribute50 {
            get {
                return ResourceManager.GetString("attribute50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patient.
        /// </summary>
        internal static string attribute51 {
            get {
                return ResourceManager.GetString("attribute51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relaxed.
        /// </summary>
        internal static string attribute52 {
            get {
                return ResourceManager.GetString("attribute52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self-conscious.
        /// </summary>
        internal static string attribute53 {
            get {
                return ResourceManager.GetString("attribute53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spontaneous.
        /// </summary>
        internal static string attribute54 {
            get {
                return ResourceManager.GetString("attribute54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wise.
        /// </summary>
        internal static string attribute55 {
            get {
                return ResourceManager.GetString("attribute55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brave.
        /// </summary>
        internal static string attribute56 {
            get {
                return ResourceManager.GetString("attribute56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complex.
        /// </summary>
        internal static string attribute57 {
            get {
                return ResourceManager.GetString("attribute57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extroverted.
        /// </summary>
        internal static string attribute58 {
            get {
                return ResourceManager.GetString("attribute58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idealistic.
        /// </summary>
        internal static string attribute59 {
            get {
                return ResourceManager.GetString("attribute59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knowledgeable.
        /// </summary>
        internal static string attribute6 {
            get {
                return ResourceManager.GetString("attribute6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kind.
        /// </summary>
        internal static string attribute60 {
            get {
                return ResourceManager.GetString("attribute60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modest.
        /// </summary>
        internal static string attribute61 {
            get {
                return ResourceManager.GetString("attribute61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to powerful.
        /// </summary>
        internal static string attribute62 {
            get {
                return ResourceManager.GetString("attribute62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to religious.
        /// </summary>
        internal static string attribute63 {
            get {
                return ResourceManager.GetString("attribute63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sensible.
        /// </summary>
        internal static string attribute64 {
            get {
                return ResourceManager.GetString("attribute64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sympathetic.
        /// </summary>
        internal static string attribute65 {
            get {
                return ResourceManager.GetString("attribute65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to witty.
        /// </summary>
        internal static string attribute66 {
            get {
                return ResourceManager.GetString("attribute66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nervous.
        /// </summary>
        internal static string attribute7 {
            get {
                return ResourceManager.GetString("attribute7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proud.
        /// </summary>
        internal static string attribute8 {
            get {
                return ResourceManager.GetString("attribute8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to responsive.
        /// </summary>
        internal static string attribute9 {
            get {
                return ResourceManager.GetString("attribute9", resourceCulture);
            }
        }
    }
}
